version: 2

models:
  - name: dim_users
    description: User dimension table with their first touchpoints
    columns:
      - name: user_id
        description: Primary key for users
        tests:
          - unique
          - not_null

  - name: fct_sessions
    description: Session facts with aggregated metrics
    columns:
      - name: session_id
        description: Primary key for sessions
        tests:
          - unique
          - not_null
      - name: session_start
        tests:
          - not_null
      - name: user_id
        tests:
          - relationships:
              to: ref('dim_users')
              field: user_id

  - name: fct_user_journeys
    description: Detailed user navigation paths
    columns:
      - name: user_id
        tests:
          - relationships:
              to: ref('dim_users')
              field: user_id
      - name: session_id
        tests:
          - relationships:
              to: ref('fct_sessions')
              field: session_id
